src/Entity/Optreden.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OptredenRepository")
 */
class Optreden
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $artiest_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $aanvang;

    /**
     * @ORM\Column(type="date")
     */
    private $datum;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zaal;

    /**
     * @ORM\Column(type="integer")
     */
    private $maxseats;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtiestId(): ?int
    {
        return $this->artiest_id;
    }

    public function setArtiestId(int $artiest_id): self
    {
        $this->artiest_id = $artiest_id;

        return $this;
    }

    public function getAanvang(): ?\DateTimeInterface
    {
        return $this->aanvang;
    }

    public function setAanvang(\DateTimeInterface $aanvang): self
    {
        $this->aanvang = $aanvang;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getZaal(): ?string
    {
        return $this->zaal;
    }

    public function setZaal(string $zaal): self
    {
        $this->zaal = $zaal;

        return $this;
    }

    public function getMaxseats(): ?int
    {
        return $this->maxseats;
    }

    public function setMaxseats(int $maxseats): self
    {
        $this->maxseats = $maxseats;

        return $this;
    }
}

src/Form/OptredenType.php
<?php

namespace App\Form;

use App\Entity\Optreden;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OptredenType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('artiest_id')
            ->add('aanvang')
            ->add('datum')
            ->add('zaal')
            ->add('maxseats')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Optreden::class,
        ]);
    }
}

src/Controller/OptredenController.php
<?php

namespace App\Controller;

use App\Entity\Optreden;
use App\Form\OptredenType;
use App\Repository\OptredenRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/optreden")
 */
class OptredenController extends AbstractController
{
    /**
     * @Route("/", name="optreden_index", methods={"GET"})
     */
    public function index(OptredenRepository $optredenRepository): Response
    {
        return $this->render('optreden/index.html.twig', [
            'optredens' => $optredenRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="optreden_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $optreden = new Optreden();
        $form = $this->createForm(OptredenType::class, $optreden);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($optreden);
            $entityManager->flush();

            return $this->redirectToRoute('optreden_index');
        }

        return $this->render('optreden/new.html.twig', [
            'optreden' => $optreden,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="optreden_show", methods={"GET"})
     */
    public function show(Optreden $optreden): Response
    {
        return $this->render('optreden/show.html.twig', [
            'optreden' => $optreden,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="optreden_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Optreden $optreden): Response
    {
        $form = $this->createForm(OptredenType::class, $optreden);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('optreden_index');
        }

        return $this->render('optreden/edit.html.twig', [
            'optreden' => $optreden,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="optreden_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Optreden $optreden): Response
    {
        if ($this->isCsrfTokenValid('delete'.$optreden->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($optreden);
            $entityManager->flush();
        }

        return $this->redirectToRoute('optreden_index');
    }
}

templates/optreden/_delete_form.html.twig
<form method="post" action="{{ path('optreden_delete', {'id': optreden.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ optreden.id) }}">
    <button class="btn">Delete</button>
</form>

templates/optreden/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/optreden/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Optreden{% endblock %}

{% block body %}
    <h1>Edit Optreden</h1>

    {{ include('optreden/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('optreden_index') }}">back to list</a>

    {{ include('optreden/_delete_form.html.twig') }}
{% endblock %}

templates/optreden/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Optreden index{% endblock %}

{% block body %}
    <h1>Optreden index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Artiest_id</th>
                <th>Aanvang</th>
                <th>Datum</th>
                <th>Zaal</th>
                <th>Maxseats</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for optreden in optredens %}
            <tr>
                <td>{{ optreden.id }}</td>
                <td>{{ optreden.artiestId }}</td>
                <td>{{ optreden.aanvang ? optreden.aanvang|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ optreden.datum ? optreden.datum|date('Y-m-d') : '' }}</td>
                <td>{{ optreden.zaal }}</td>
                <td>{{ optreden.maxseats }}</td>
                <td>
                    <a href="{{ path('optreden_show', {'id': optreden.id}) }}">show</a>
                    <a href="{{ path('optreden_edit', {'id': optreden.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('optreden_new') }}">Create new</a>
{% endblock %}

templates/optreden/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Optreden{% endblock %}

{% block body %}
    <h1>Create new Optreden</h1>

    {{ include('optreden/_form.html.twig') }}

    <a href="{{ path('optreden_index') }}">back to list</a>
{% endblock %}

templates/optreden/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Optreden{% endblock %}

{% block body %}
    <h1>Optreden</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ optreden.id }}</td>
            </tr>
            <tr>
                <th>Artiest_id</th>
                <td>{{ optreden.artiestId }}</td>
            </tr>
            <tr>
                <th>Aanvang</th>
                <td>{{ optreden.aanvang ? optreden.aanvang|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Datum</th>
                <td>{{ optreden.datum ? optreden.datum|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Zaal</th>
                <td>{{ optreden.zaal }}</td>
            </tr>
            <tr>
                <th>Maxseats</th>
                <td>{{ optreden.maxseats }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('optreden_index') }}">back to list</a>

    <a href="{{ path('optreden_edit', {'id': optreden.id}) }}">edit</a>

    {{ include('optreden/_delete_form.html.twig') }}
{% endblock %}